services:
  dev:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    command: fastapi dev main.py --host 0.0.0.0
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app