services:
  dev:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - UPLOAD_DIRECTORY=${UPLOAD_DIRECTORY}
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app
      - /tmp/uploads:${UPLOAD_DIRECTORY}
    command: fastapi dev main.py --host 0.0.0.0

  prod:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - UPLOAD_DIRECTORY=${UPLOAD_DIRECTORY}
    ports:
      - '80:8000'
    volumes:
      - /tmp/uploads:${UPLOAD_DIRECTORY}
    command: fastapi run main.py