from typing import IO, Any, AsyncGenerator, Protocol, runtime_checkable


@runtime_checkable
class StorageProtocol(Protocol):
    async def get(self, key: str) -> bytes: ...

    async def upload(self, filename: str, file: IO[bytes], sub_path: str) -> str: ...

    async def delete(self, key: str) -> None: ...

    async def list_files(self, key: str) -> AsyncGenerator[str, Any]: ...
